---

- block:
    - name: Detect missing Python versions
      ansible.builtin.command: >
        {{ python_paths[item]|default(python_default_path) }} --version
      changed_when: _python_command is failure
      check_mode: false
      failed_when: false
      loop: '{{ python_versions }}'
      register: _python_command

    - ansible.builtin.set_fact:
        python_missing_versions: "{{ _python_command.results|selectattr('changed')|map(attribute='item')|list }}"
  tags: [python, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
