---

- block:
    - name: Enable Red Hat repositories
      rhsm_repository:
        name: '{{ python_rhsm_repositories }}'
        state: enabled

    - name: Install Python packages
      package:
        name: '{{ python_packages }}'
        state: present

    - include_tasks: get-versions.yml

    - assert:
        that:
          - not python_missing_versions|default([])
  become: yes
  tags: [python, packages]
