---

- block:
    - name: Enable Red Hat repositories
      ansible.builtin.rhsm_repository:
        name: '{{ python_rhsm_repositories }}'
        state: enabled

    - name: Install Python packages
      ansible.builtin.package:
        name: '{{ python_packages }}'
        state: present

    - include_tasks: get-versions.yml

    - ansible.builtin.assert:
        that:
          - not python_missing_versions|default([])
  become: '{{ do_become }}'
  tags: [python, packages]

...
