---

- name: Install Python build dependencies
  apt:
    name: python
    state: build-dep
  become: '{{ do_become }}'
  tags: [python, packages] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
