---

- name: Install Python build dependencies
  ansible.builtin.command:
    yum-builddep --assume{{ 'no' if ansible_check_mode else 'yes' }} {{ python_build_install_dependencies_of }}
  become: '{{ do_become }}'
  changed_when: "'No uninstalled build requires' not in _python_build_dep.stdout|default('')"
  check_mode: false
  failed_when: _python_build_dep is failure and 'Exiting on user command' not in _python_build_dep.stdout
  register: _python_build_dep
  tags: [python, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
